name: Deploy to Remote Test Server

on:
  push:
    branches:
      - master   # triggers only when merging into master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to remote server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml cloud_user@0f319178341c.mylabserver.com:/home/cloud_user/docker-compose.yml
          scp -o StrictHostKeyChecking=no docker-compose.es.yml cloud_user@0f319178341c.mylabserver.com:/home/cloud_user/docker-compose.es.yml

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no cloud_user@0f319178341c.mylabserver.com << 'EOF'
            cd /home/cloud_user
            docker compose -f docker-compose.yml -f docker-compose.es.yml pull
            docker compose -f docker-compose.yml -f docker-compose.es.yml up -d --remove-orphans
          EOF
